release:
  prerelease: true

builds:
- binary: awsmfa
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.buildTime={{.Date}}`.

archive:
  format: tar.gz

  format_overrides:
  - goos: windows
    format: zip

